
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from warnings import catch_warnings
with catch_warnings(record=True):
    import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1700680381bdbfbc1abe9774f96881801b24d6ca",
 "version": "0.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
